# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: photonHit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='photonHit.proto',
  package='hitPhotons',
  syntax='proto3',
  serialized_pb=_b('\n\x0fphotonHit.proto\x12\nhitPhotons\"\xc6\x02\n\x06Photon\x12\r\n\x05PMTID\x18\x01 \x01(\x05\x12\x0c\n\x04Time\x18\x02 \x01(\x01\x12\x15\n\rKineticEnergy\x18\x03 \x01(\x01\x12\x0c\n\x04posX\x18\x04 \x01(\x01\x12\x0c\n\x04posY\x18\x05 \x01(\x01\x12\x0c\n\x04posZ\x18\x06 \x01(\x01\x12\x0c\n\x04momX\x18\x07 \x01(\x01\x12\x0c\n\x04momY\x18\x08 \x01(\x01\x12\x0c\n\x04momZ\x18\t \x01(\x01\x12\x0c\n\x04polX\x18\n \x01(\x01\x12\x0c\n\x04polY\x18\x0b \x01(\x01\x12\x0c\n\x04polZ\x18\x0c \x01(\x01\x12\x0f\n\x07trackID\x18\x0e \x01(\x05\x12-\n\x06origin\x18\x0f \x01(\x0e\x32\x1d.hitPhotons.Photon.OriginFlag\"J\n\nOriginFlag\x12\r\n\tCHERENKOV\x10\x00\x12\x11\n\rSCINTILLATION\x10\x01\x12\x0e\n\nREEMISSION\x10\x02\x12\n\n\x06\x43HROMA\x10\x03\"?\n\nPhotonHits\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\"\n\x06photon\x18\x02 \x03(\x0b\x32\x12.hitPhotons.Photonb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PHOTON_ORIGINFLAG = _descriptor.EnumDescriptor(
  name='OriginFlag',
  full_name='hitPhotons.Photon.OriginFlag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHERENKOV', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCINTILLATION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REEMISSION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHROMA', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=284,
  serialized_end=358,
)
_sym_db.RegisterEnumDescriptor(_PHOTON_ORIGINFLAG)


_PHOTON = _descriptor.Descriptor(
  name='Photon',
  full_name='hitPhotons.Photon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PMTID', full_name='hitPhotons.Photon.PMTID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Time', full_name='hitPhotons.Photon.Time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='KineticEnergy', full_name='hitPhotons.Photon.KineticEnergy', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posX', full_name='hitPhotons.Photon.posX', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posY', full_name='hitPhotons.Photon.posY', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posZ', full_name='hitPhotons.Photon.posZ', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momX', full_name='hitPhotons.Photon.momX', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momY', full_name='hitPhotons.Photon.momY', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momZ', full_name='hitPhotons.Photon.momZ', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polX', full_name='hitPhotons.Photon.polX', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polY', full_name='hitPhotons.Photon.polY', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polZ', full_name='hitPhotons.Photon.polZ', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trackID', full_name='hitPhotons.Photon.trackID', index=12,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='hitPhotons.Photon.origin', index=13,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PHOTON_ORIGINFLAG,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=358,
)


_PHOTONHITS = _descriptor.Descriptor(
  name='PhotonHits',
  full_name='hitPhotons.PhotonHits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='hitPhotons.PhotonHits.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='photon', full_name='hitPhotons.PhotonHits.photon', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=423,
)

_PHOTON.fields_by_name['origin'].enum_type = _PHOTON_ORIGINFLAG
_PHOTON_ORIGINFLAG.containing_type = _PHOTON
_PHOTONHITS.fields_by_name['photon'].message_type = _PHOTON
DESCRIPTOR.message_types_by_name['Photon'] = _PHOTON
DESCRIPTOR.message_types_by_name['PhotonHits'] = _PHOTONHITS

Photon = _reflection.GeneratedProtocolMessageType('Photon', (_message.Message,), dict(
  DESCRIPTOR = _PHOTON,
  __module__ = 'photonHit_pb2'
  # @@protoc_insertion_point(class_scope:hitPhotons.Photon)
  ))
_sym_db.RegisterMessage(Photon)

PhotonHits = _reflection.GeneratedProtocolMessageType('PhotonHits', (_message.Message,), dict(
  DESCRIPTOR = _PHOTONHITS,
  __module__ = 'photonHit_pb2'
  # @@protoc_insertion_point(class_scope:hitPhotons.PhotonHits)
  ))
_sym_db.RegisterMessage(PhotonHits)


# @@protoc_insertion_point(module_scope)
